In [3]:
#OPEN FILES AND IMPORT LIBRARIES
import pandas as pd
import re
import matplotlib.pyplot as plt

df0 = pd.read_csv("green_tripdata_2018-12.csv")

In [4]:
#Check structure
df0.shape

(685373, 19)

In [5]:
#Display first lines
df0.head(5)

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type
0,2,2018-12-01 00:23:25,2018-12-01 00:24:47,N,1,193,193,1,0.00,3.0,0.5,0.5,0.00,0.0,NaN,0.3,4.30,2,1.0
1,2,2018-11-30 23:58:31,2018-12-01 00:21:53,N,1,80,82,2,5.75,21.0,0.5,0.5,0.00,0.0,NaN,0.3,22.30,2,1.0
2,2,2018-12-01 00:21:03,2018-12-01 00:30:15,N,1,225,225,1,1.55,8.0,0.5,0.5,1.86,0.0,NaN,0.3,11.16,1,1.0
3,2,2018-12-01 00:15:56,2018-12-01 00:23:26,N,1,75,236,2,1.32,7.0,0.5,0.5,0.00,0.0,NaN,0.3,8.30,1,1.0
4,2,2018-12-01 00:28:32,2018-12-01 00:30:33,N,1,75,75,2,0.68,4.0,0.5,0.5,1.06,0.0,NaN,0.3,6.36,1,1.0

In [6]:
#Check that the data types are correct
'''Agregation vectors should be floats or ints not objects, if object then there may be bad characters'''
df0.dtypes

VendorID                   int64
lpep_pickup_datetime      object
lpep_dropoff_datetime     object
store_and_fwd_flag        object
RatecodeID                 int64
PULocationID               int64
DOLocationID               int64
passenger_count            int64
trip_distance            float64
fare_amount              float64
extra                    float64
mta_tax                  float64
tip_amount               float64
tolls_amount             float64
ehail_fee                float64
improvement_surcharge    float64
total_amount             float64
payment_type               int64
trip_type                float64
dtype: object

In [7]:
#Name of columns and index of each column:
''' This function provides a clean output of columns and indexes'''
def col(dfs):
    list_col = list(dfs.columns.values)
    list_number_col = []
    zip_list = []
    for i in range(0, len(list_col)):
        list_number_col.append(i)
    zip_list = list(zip(list_number_col,list_col))
    #[(0, 'event_date'), (1, 'id'), (2, 'dimension_1')]
    for i in zip_list:
        a = i[0]
        b = i[1]
        print(str(a) + "|" +  b)
print(col(df0))

0|VendorID
1|lpep_pickup_datetime
2|lpep_dropoff_datetime
3|store_and_fwd_flag
4|RatecodeID
5|PULocationID
6|DOLocationID
7|passenger_count
8|trip_distance
9|fare_amount
10|extra
11|mta_tax
12|tip_amount
13|tolls_amount
14|ehail_fee
15|improvement_surcharge
16|total_amount
17|payment_type
18|trip_type
None

In [8]:
#Check unique values of columns
'''Use this line to have a close look at the data'''
#set(list(df0.iloc[:,17]))
sorted(set(list(df0.iloc[:,2])), reverse=True)

['2019-03-11 22:34:23',
 '2019-01-28 05:44:20',
 '2019-01-14 21:25:36',
 '2019-01-06 22:04:29',
 '2019-01-06 21:55:54',
 '2019-01-03 10:36:19',
 '2019-01-03 10:27:59',
 '2019-01-03 02:39:36',
 '2019-01-03 02:14:03',
 '2019-01-02 22:22:26',
 '2019-01-01 23:50:40',
 '2019-01-01 23:39:40',
 '2019-01-01 23:27:47',
 '2019-01-01 23:23:25',
 '2019-01-01 23:09:52',
 '2019-01-01 22:55:39',
 '2019-01-01 22:41:41',
 '2019-01-01 22:38:35',
 '2019-01-01 22:36:05',
 '2019-01-01 22:21:38',
 '2019-01-01 22:07:17',
 '2019-01-01 22:04:59',
 '2019-01-01 21:42:21',
 '2019-01-01 21:27:55',
 '2019-01-01 21:13:06',
 '2019-01-01 21:01:24',
 '2019-01-01 20:59:58',
 '2019-01-01 20:38:28',
 '2019-01-01 20:36:35',
 '2019-01-01 20:35:37',
 '2019-01-01 20:18:07',
 '2019-01-01 20:12:15',
 '2019-01-01 19:42:37',
 '2019-01-01 19:30:50',
 '2019-01-01 19:21:29',
 '2019-01-01 19:16:31',
 '2019-01-01 19:13:12',
 '2019-01-01 19:08:34',
 '2019-01-01 19:08:11',
 '2019-01-01 19:07:35',
 '2019-01-01 19:06:26',
 '2019-01-01 19:00:58',
 '2019-01-01 18:58:18',
 '2019-01-01 18:43:33',
 '2019-01-01 18:32:53',
 '2019-01-01 18:20:21',
 '2019-01-01 18:11:53',
 '2019-01-01 18:09:10',
 '2019-01-01 17:54:04',
 '2019-01-01 17:52:01',
 '2019-01-01 17:50:53',
 '2019-01-01 17:47:39',
 '2019-01-01 17:46:15',
 '2019-01-01 17:44:42',
 '2019-01-01 17:42:32',
 '2019-01-01 17:23:11',
 '2019-01-01 17:10:04',
 '2019-01-01 16:57:42',
 '2019-01-01 16:53:56',
 '2019-01-01 16:35:11',
 '2019-01-01 16:34:20',
 '2019-01-01 16:18:16',
 '2019-01-01 15:33:51',
 '2019-01-01 15:21:57',
 '2019-01-01 15:19:28',
 '2019-01-01 15:19:11',
 '2019-01-01 15:16:12',
 '2019-01-01 15:15:35',
 '2019-01-01 15:15:25',
 '2019-01-01 15:12:44',
 '2019-01-01 15:11:14',
 '2019-01-01 15:10:32',
 '2019-01-01 15:02:35',
 '2019-01-01 14:53:39',
 '2019-01-01 14:39:52',
 '2019-01-01 14:31:27',
 '2019-01-01 14:26:11',
 '2019-01-01 13:37:53',
 '2019-01-01 13:32:15',
 '2019-01-01 13:10:43',
 '2019-01-01 13:00:12',
 '2019-01-01 12:56:49',
 '2019-01-01 12:42:10',
 '2019-01-01 12:13:52',
 '2019-01-01 12:13:25',
 '2019-01-01 12:10:15',
 '2019-01-01 11:48:01',
 '2019-01-01 11:42:28',
 '2019-01-01 11:13:02',
 '2019-01-01 11:08:06',
 '2019-01-01 10:12:19',
 '2019-01-01 10:06:06',
 '2019-01-01 09:49:24',
 '2019-01-01 09:46:37',
 '2019-01-01 09:43:12',
 '2019-01-01 09:40:38',
 '2019-01-01 09:37:28',
 '2019-01-01 09:31:18',
 '2019-01-01 09:26:31',
 '2019-01-01 08:10:20',
 '2019-01-01 07:55:15',
 '2019-01-01 07:49:02',
 '2019-01-01 07:37:47',
 '2019-01-01 07:26:21',
 '2019-01-01 07:23:14',
 '2019-01-01 06:47:08',
 '2019-01-01 06:41:09',
 '2019-01-01 06:01:02',
 '2019-01-01 06:00:03',
 '2019-01-01 05:56:09',
 '2019-01-01 04:17:07',
 '2019-01-01 03:01:03',
 '2019-01-01 02:26:58',
 '2019-01-01 02:19:57',
 '2019-01-01 02:15:13',
 '2019-01-01 01:31:32',
 '2019-01-01 01:17:25',
 '2019-01-01 01:13:08',
 '2019-01-01 01:09:32',
 '2019-01-01 01:07:35',
 '2019-01-01 01:04:58',
 '2019-01-01 00:46:29',
 '2019-01-01 00:40:55',
 '2019-01-01 00:40:03',
 '2019-01-01 00:37:20',
 '2019-01-01 00:37:07',
 '2019-01-01 00:36:01',
 '2019-01-01 00:34:34',
 '2019-01-01 00:30:52',
 '2019-01-01 00:27:42',
 '2019-01-01 00:26:54',
 '2019-01-01 00:26:13',
 '2019-01-01 00:25:59',
 '2019-01-01 00:25:55',
 '2019-01-01 00:24:07',
 '2019-01-01 00:24:03',
 '2019-01-01 00:23:53',
 '2019-01-01 00:22:48',
 '2019-01-01 00:22:38',
 '2019-01-01 00:21:55',
 '2019-01-01 00:21:20',
 '2019-01-01 00:19:43',
 '2019-01-01 00:19:32',
 '2019-01-01 00:18:41',
 '2019-01-01 00:17:34',
 '2019-01-01 00:17:20',
 '2019-01-01 00:15:14',
 '2019-01-01 00:15:08',
 '2019-01-01 00:14:53',
 '2019-01-01 00:14:49',
 '2019-01-01 00:14:45',
 '2019-01-01 00:14:39',
 '2019-01-01 00:14:36',
 '2019-01-01 00:14:15',
 '2019-01-01 00:14:02',
 '2019-01-01 00:13:55',
 '2019-01-01 00:13:48',
 '2019-01-01 00:13:44',
 '2019-01-01 00:13:28',
 '2019-01-01 00:12:46',
 '2019-01-01 00:12:38',
 '2019-01-01 00:12:01',
 '2019-01-01 00:11:46',
 '2019-01-01 00:11:15',
 '2019-01-01 00:11:03',
 '2019-01-01 00:10:58',
 '2019-01-01 00:10:42',
 '2019-01-01 00:10:30',
 '2019-01-01 00:10:27',
 '2019-01-01 00:10:26',
 '2019-01-01 00:09:43',
 '2019-01-01 00:09:25',
 '2019-01-01 00:09:21',
 '2019-01-01 00:08:49',
 '2019-01-01 00:08:23',
 '2019-01-01 00:08:18',
 '2019-01-01 00:08:15',
 '2019-01-01 00:07:58',
 '2019-01-01 00:07:51',
 '2019-01-01 00:07:44',
 '2019-01-01 00:07:34',
 '2019-01-01 00:07:30',
 '2019-01-01 00:07:02',
 '2019-01-01 00:07:01',
 '2019-01-01 00:06:41',
 '2019-01-01 00:06:29',
 '2019-01-01 00:06:24',
 '2019-01-01 00:06:19',
 '2019-01-01 00:06:05',
 '2019-01-01 00:06:00',
 '2019-01-01 00:05:58',
 '2019-01-01 00:05:50',
 '2019-01-01 00:05:41',
 '2019-01-01 00:05:40',
 '2019-01-01 00:05:26',
 '2019-01-01 00:05:16',
 '2019-01-01 00:05:02',
 '2019-01-01 00:05:00',
 '2019-01-01 00:04:56',
 '2019-01-01 00:04:51',
 '2019-01-01 00:04:49',
 '2019-01-01 00:04:46',
 '2019-01-01 00:04:45',
 '2019-01-01 00:04:41',
 '2019-01-01 00:04:24',
 '2019-01-01 00:04:21',
 '2019-01-01 00:04:18',
 '2019-01-01 00:04:15',
 '2019-01-01 00:04:13',
 '2019-01-01 00:04:06',
 '2019-01-01 00:04:04',
 '2019-01-01 00:03:41',
 '2019-01-01 00:03:33',
 '2019-01-01 00:03:27',
 '2019-01-01 00:03:15',
 '2019-01-01 00:03:12',
 '2019-01-01 00:03:11',
 '2019-01-01 00:03:04',
 '2019-01-01 00:03:03',
 '2019-01-01 00:03:01',
 '2019-01-01 00:02:52',
 '2019-01-01 00:02:33',
 '2019-01-01 00:02:30',
 '2019-01-01 00:02:19',
 '2019-01-01 00:02:17',
 '2019-01-01 00:02:13',
 '2019-01-01 00:02:12',
 '2019-01-01 00:01:55',
 '2019-01-01 00:01:53',
 '2019-01-01 00:01:50',
 '2019-01-01 00:01:47',
 '2019-01-01 00:01:43',
 '2019-01-01 00:01:38',
 '2019-01-01 00:01:34',
 '2019-01-01 00:01:33',
 '2019-01-01 00:01:32',
 '2019-01-01 00:01:28',
 '2019-01-01 00:01:26',
 '2019-01-01 00:01:21',
 '2019-01-01 00:01:19',
 '2019-01-01 00:01:14',
 '2019-01-01 00:01:11',
 '2019-01-01 00:01:08',
 '2019-01-01 00:01:03',
 '2019-01-01 00:01:02',
 '2019-01-01 00:00:52',
 '2019-01-01 00:00:46',
 '2019-01-01 00:00:45',
 '2019-01-01 00:00:40',
 '2019-01-01 00:00:24',
 '2019-01-01 00:00:18',
 '2019-01-01 00:00:00',
 '2018-12-31 23:59:57',
 '2018-12-31 23:59:55',
 '2018-12-31 23:59:50',
 '2018-12-31 23:59:40',
 '2018-12-31 23:59:37',
 '2018-12-31 23:59:34',
 '2018-12-31 23:59:25',
 '2018-12-31 23:59:23',
 '2018-12-31 23:59:17',
 '2018-12-31 23:59:06',
 '2018-12-31 23:59:05',
 '2018-12-31 23:58:58',
 '2018-12-31 23:58:56',
 '2018-12-31 23:58:34',
 '2018-12-31 23:58:29',
 '2018-12-31 23:58:28',
 '2018-12-31 23:58:27',
 '2018-12-31 23:58:25',
 '2018-12-31 23:58:20',
 '2018-12-31 23:58:17',
 '2018-12-31 23:58:09',
 '2018-12-31 23:58:01',
 '2018-12-31 23:57:59',
 '2018-12-31 23:57:58',
 '2018-12-31 23:57:57',
 '2018-12-31 23:57:56',
 '2018-12-31 23:57:55',
 '2018-12-31 23:57:43',
 '2018-12-31 23:57:38',
 '2018-12-31 23:57:35',
 '2018-12-31 23:57:34',
 '2018-12-31 23:57:28',
 '2018-12-31 23:57:25',
 '2018-12-31 23:57:23',
 '2018-12-31 23:57:21',
 '2018-12-31 23:57:20',
 '2018-12-31 23:57:15',
 '2018-12-31 23:57:12',
 '2018-12-31 23:57:08',
 '2018-12-31 23:57:05',
 '2018-12-31 23:56:59',
 '2018-12-31 23:56:56',
 '2018-12-31 23:56:54',
 '2018-12-31 23:56:50',
 '2018-12-31 23:56:47',
 '2018-12-31 23:56:41',
 '2018-12-31 23:56:36',
 '2018-12-31 23:56:26',
 '2018-12-31 23:56:23',
 '2018-12-31 23:56:22',
 '2018-12-31 23:56:08',
 '2018-12-31 23:56:06',
 '2018-12-31 23:56:02',
 '2018-12-31 23:55:44',
 '2018-12-31 23:55:42',
 '2018-12-31 23:55:39',
 '2018-12-31 23:55:26',
 '2018-12-31 23:55:25',
 '2018-12-31 23:55:24',
 '2018-12-31 23:55:23',
 '2018-12-31 23:55:22',
 '2018-12-31 23:55:15',
 '2018-12-31 23:55:14',
 '2018-12-31 23:55:13',
 '2018-12-31 23:55:06',
 '2018-12-31 23:55:04',
 '2018-12-31 23:55:02',
 '2018-12-31 23:54:47',
 '2018-12-31 23:54:40',
 '2018-12-31 23:54:39',
 '2018-12-31 23:54:33',
 '2018-12-31 23:54:29',
 '2018-12-31 23:54:27',
 '2018-12-31 23:54:25',
 '2018-12-31 23:54:20',
 '2018-12-31 23:54:16',
 '2018-12-31 23:54:15',
 '2018-12-31 23:54:14',
 '2018-12-31 23:54:09',
 '2018-12-31 23:54:07',
 '2018-12-31 23:54:02',
 '2018-12-31 23:53:51',
 '2018-12-31 23:53:49',
 '2018-12-31 23:53:46',
 '2018-12-31 23:53:43',
 '2018-12-31 23:53:40',
 '2018-12-31 23:53:39',
 '2018-12-31 23:53:37',
 '2018-12-31 23:53:36',
 '2018-12-31 23:53:32',
 '2018-12-31 23:53:30',
 '2018-12-31 23:53:29',
 '2018-12-31 23:53:28',
 '2018-12-31 23:53:24',
 '2018-12-31 23:53:15',
 '2018-12-31 23:53:11',
 '2018-12-31 23:53:09',
 '2018-12-31 23:53:08',
 '2018-12-31 23:53:03',
 '2018-12-31 23:52:51',
 '2018-12-31 23:52:43',
 '2018-12-31 23:52:42',
 '2018-12-31 23:52:41',
 '2018-12-31 23:52:36',
 '2018-12-31 23:52:32',
 '2018-12-31 23:52:30',
 '2018-12-31 23:52:26',
 '2018-12-31 23:52:20',
 '2018-12-31 23:52:15',
 '2018-12-31 23:52:14',
 '2018-12-31 23:52:12',
 '2018-12-31 23:52:07',
 '2018-12-31 23:52:00',
 '2018-12-31 23:51:59',
 '2018-12-31 23:51:55',
 '2018-12-31 23:51:52',
 '2018-12-31 23:51:50',
 '2018-12-31 23:51:49',
 '2018-12-31 23:51:48',
 '2018-12-31 23:51:45',
 '2018-12-31 23:51:42',
 '2018-12-31 23:51:41',
 '2018-12-31 23:51:40',
 '2018-12-31 23:51:35',
 '2018-12-31 23:51:27',
 '2018-12-31 23:51:19',
 '2018-12-31 23:51:04',
 '2018-12-31 23:50:58',
 '2018-12-31 23:50:57',
 '2018-12-31 23:50:48',
 '2018-12-31 23:50:46',
 '2018-12-31 23:50:44',
 '2018-12-31 23:50:40',
 '2018-12-31 23:50:39',
 '2018-12-31 23:50:27',
 '2018-12-31 23:50:24',
 '2018-12-31 23:50:22',
 '2018-12-31 23:50:17',
 '2018-12-31 23:50:13',
 '2018-12-31 23:50:09',
 '2018-12-31 23:50:04',
 '2018-12-31 23:50:02',
 '2018-12-31 23:49:57',
 '2018-12-31 23:49:50',
 '2018-12-31 23:49:49',
 '2018-12-31 23:49:48',
 '2018-12-31 23:49:46',
 '2018-12-31 23:49:45',
 '2018-12-31 23:49:42',
 '2018-12-31 23:49:28',
 '2018-12-31 23:49:27',
 '2018-12-31 23:49:19',
 '2018-12-31 23:49:17',
 '2018-12-31 23:49:16',
 '2018-12-31 23:49:14',
 '2018-12-31 23:49:06',
 '2018-12-31 23:49:01',
 '2018-12-31 23:49:00',
 '2018-12-31 23:48:58',
 '2018-12-31 23:48:54',
 '2018-12-31 23:48:47',
 '2018-12-31 23:48:45',
 '2018-12-31 23:48:44',
 '2018-12-31 23:48:42',
 '2018-12-31 23:48:41',
 '2018-12-31 23:48:24',
 '2018-12-31 23:48:06',
 '2018-12-31 23:48:05',
 '2018-12-31 23:47:54',
 '2018-12-31 23:47:50',
 '2018-12-31 23:47:42',
 '2018-12-31 23:47:36',
 '2018-12-31 23:47:29',
 '2018-12-31 23:47:27',
 '2018-12-31 23:47:20',
 '2018-12-31 23:47:17',
 '2018-12-31 23:47:10',
 '2018-12-31 23:47:06',
 '2018-12-31 23:46:58',
 '2018-12-31 23:46:57',
 '2018-12-31 23:46:56',
 '2018-12-31 23:46:46',
 '2018-12-31 23:46:41',
 '2018-12-31 23:46:37',
 '2018-12-31 23:46:35',
 '2018-12-31 23:46:30',
 '2018-12-31 23:46:17',
 '2018-12-31 23:46:15',
 '2018-12-31 23:46:10',
 '2018-12-31 23:46:07',
 '2018-12-31 23:46:04',
 '2018-12-31 23:46:03',
 '2018-12-31 23:46:00',
 '2018-12-31 23:45:57',
 '2018-12-31 23:45:55',
 '2018-12-31 23:45:54',
 '2018-12-31 23:45:46',
 '2018-12-31 23:45:42',
 '2018-12-31 23:45:34',
 '2018-12-31 23:45:31',
 '2018-12-31 23:45:30',
 '2018-12-31 23:45:26',
 '2018-12-31 23:45:23',
 '2018-12-31 23:45:22',
 '2018-12-31 23:45:21',
 '2018-12-31 23:45:19',
 '2018-12-31 23:45:18',
 '2018-12-31 23:45:13',
 '2018-12-31 23:45:10',
 '2018-12-31 23:45:06',
 '2018-12-31 23:45:03',
 '2018-12-31 23:44:54',
 '2018-12-31 23:44:52',
 '2018-12-31 23:44:51',
 '2018-12-31 23:44:48',
 '2018-12-31 23:44:41',
 '2018-12-31 23:44:39',
 '2018-12-31 23:44:36',
 '2018-12-31 23:44:31',
 '2018-12-31 23:44:30',
 '2018-12-31 23:44:28',
 '2018-12-31 23:44:26',
 '2018-12-31 23:44:25',
 '2018-12-31 23:44:23',
 '2018-12-31 23:44:17',
 '2018-12-31 23:44:11',
 '2018-12-31 23:44:10',
 '2018-12-31 23:44:07',
 '2018-12-31 23:44:06',
 '2018-12-31 23:44:00',
 '2018-12-31 23:43:59',
 '2018-12-31 23:43:57',
 '2018-12-31 23:43:40',
 '2018-12-31 23:43:36',
 '2018-12-31 23:43:28',
 '2018-12-31 23:43:27',
 '2018-12-31 23:43:22',
 '2018-12-31 23:43:19',
 '2018-12-31 23:43:08',
 '2018-12-31 23:42:59',
 '2018-12-31 23:42:58',
 '2018-12-31 23:42:57',
 '2018-12-31 23:42:54',
 '2018-12-31 23:42:49',
 '2018-12-31 23:42:41',
 '2018-12-31 23:42:40',
 '2018-12-31 23:42:34',
 '2018-12-31 23:42:25',
 '2018-12-31 23:42:24',
 '2018-12-31 23:42:21',
 '2018-12-31 23:42:07',
 '2018-12-31 23:42:06',
 '2018-12-31 23:42:05',
 '2018-12-31 23:41:56',
 '2018-12-31 23:41:55',
 '2018-12-31 23:41:54',
 '2018-12-31 23:41:47',
 '2018-12-31 23:41:45',
 '2018-12-31 23:41:37',
 '2018-12-31 23:41:24',
 '2018-12-31 23:41:23',
 '2018-12-31 23:41:17',
 '2018-12-31 23:41:15',
 '2018-12-31 23:41:14',
 '2018-12-31 23:41:07',
 '2018-12-31 23:41:06',
 '2018-12-31 23:41:04',
 '2018-12-31 23:41:03',
 '2018-12-31 23:40:55',
 '2018-12-31 23:40:53',
 '2018-12-31 23:40:47',
 '2018-12-31 23:40:46',
 '2018-12-31 23:40:45',
 '2018-12-31 23:40:25',
 '2018-12-31 23:40:22',
 '2018-12-31 23:40:16',
 '2018-12-31 23:40:13',
 '2018-12-31 23:40:09',
 '2018-12-31 23:40:01',
 '2018-12-31 23:39:59',
 '2018-12-31 23:39:54',
 '2018-12-31 23:39:52',
 '2018-12-31 23:39:49',
 '2018-12-31 23:39:47',
 '2018-12-31 23:39:46',
 '2018-12-31 23:39:40',
 '2018-12-31 23:39:32',
 '2018-12-31 23:39:28',
 '2018-12-31 23:39:17',
 '2018-12-31 23:39:14',
 '2018-12-31 23:39:13',
 '2018-12-31 23:39:09',
 '2018-12-31 23:39:04',
 '2018-12-31 23:39:03',
 '2018-12-31 23:39:01',
 '2018-12-31 23:38:57',
 '2018-12-31 23:38:56',
 '2018-12-31 23:38:54',
 '2018-12-31 23:38:48',
 '2018-12-31 23:38:41',
 '2018-12-31 23:38:40',
 '2018-12-31 23:38:36',
 '2018-12-31 23:38:34',
 '2018-12-31 23:38:32',
 '2018-12-31 23:38:30',
 '2018-12-31 23:38:29',
 '2018-12-31 23:38:28',
 '2018-12-31 23:38:23',
 '2018-12-31 23:38:22',
 '2018-12-31 23:38:16',
 '2018-12-31 23:38:09',
 '2018-12-31 23:38:06',
 '2018-12-31 23:38:02',
 '2018-12-31 23:38:00',
 '2018-12-31 23:37:55',
 '2018-12-31 23:37:50',
 '2018-12-31 23:37:43',
 '2018-12-31 23:37:40',
 '2018-12-31 23:37:38',
 '2018-12-31 23:37:37',
 '2018-12-31 23:37:33',
 '2018-12-31 23:37:31',
 '2018-12-31 23:37:23',
 '2018-12-31 23:37:19',
 '2018-12-31 23:37:08',
 '2018-12-31 23:37:05',
 '2018-12-31 23:37:04',
 '2018-12-31 23:36:52',
 '2018-12-31 23:36:45',
 '2018-12-31 23:36:44',
 '2018-12-31 23:36:43',
 '2018-12-31 23:36:40',
 '2018-12-31 23:36:31',
 '2018-12-31 23:36:29',
 '2018-12-31 23:36:24',
 '2018-12-31 23:36:22',
 '2018-12-31 23:36:21',
 '2018-12-31 23:36:19',
 '2018-12-31 23:36:18',
 '2018-12-31 23:36:17',
 '2018-12-31 23:36:11',
 '2018-12-31 23:36:09',
 '2018-12-31 23:36:05',
 '2018-12-31 23:35:50',
 '2018-12-31 23:35:48',
 '2018-12-31 23:35:44',
 '2018-12-31 23:35:43',
 '2018-12-31 23:35:40',
 '2018-12-31 23:35:37',
 '2018-12-31 23:35:30',
 '2018-12-31 23:35:26',
 '2018-12-31 23:35:25',
 '2018-12-31 23:35:20',
 '2018-12-31 23:35:15',
 '2018-12-31 23:35:14',
 '2018-12-31 23:35:13',
 '2018-12-31 23:35:10',
 '2018-12-31 23:35:06',
 '2018-12-31 23:35:00',
 '2018-12-31 23:34:52',
 '2018-12-31 23:34:46',
 '2018-12-31 23:34:32',
 '2018-12-31 23:34:27',
 '2018-12-31 23:34:23',
 '2018-12-31 23:34:20',
 '2018-12-31 23:34:18',
 '2018-12-31 23:34:17',
 '2018-12-31 23:34:08',
 '2018-12-31 23:34:03',
 '2018-12-31 23:33:51',
 '2018-12-31 23:33:50',
 '2018-12-31 23:33:37',
 '2018-12-31 23:33:31',
 '2018-12-31 23:33:30',
 '2018-12-31 23:33:28',
 '2018-12-31 23:33:27',
 '2018-12-31 23:33:25',
 '2018-12-31 23:33:22',
 '2018-12-31 23:33:19',
 '2018-12-31 23:33:14',
 '2018-12-31 23:33:13',
 '2018-12-31 23:33:10',
 '2018-12-31 23:33:08',
 '2018-12-31 23:33:05',
 '2018-12-31 23:33:04',
 '2018-12-31 23:32:59',
 '2018-12-31 23:32:58',
 '2018-12-31 23:32:56',
 '2018-12-31 23:32:51',
 '2018-12-31 23:32:50',
 '2018-12-31 23:32:48',
 '2018-12-31 23:32:36',
 '2018-12-31 23:32:33',
 '2018-12-31 23:32:32',
 '2018-12-31 23:32:31',
 '2018-12-31 23:32:23',
 '2018-12-31 23:32:18',
 '2018-12-31 23:32:16',
 '2018-12-31 23:32:14',
 '2018-12-31 23:32:06',
 '2018-12-31 23:32:04',
 '2018-12-31 23:31:58',
 '2018-12-31 23:31:55',
 '2018-12-31 23:31:54',
 '2018-12-31 23:31:45',
 '2018-12-31 23:31:42',
 '2018-12-31 23:31:41',
 '2018-12-31 23:31:37',
 '2018-12-31 23:31:28',
 '2018-12-31 23:31:26',
 '2018-12-31 23:31:23',
 '2018-12-31 23:31:17',
 '2018-12-31 23:31:08',
 '2018-12-31 23:31:00',
 '2018-12-31 23:30:56',
 '2018-12-31 23:30:54',
 '2018-12-31 23:30:53',
 '2018-12-31 23:30:47',
 '2018-12-31 23:30:46',
 '2018-12-31 23:30:45',
 '2018-12-31 23:30:42',
 '2018-12-31 23:30:41',
 '2018-12-31 23:30:38',
 '2018-12-31 23:30:33',
 '2018-12-31 23:30:28',
 '2018-12-31 23:30:25',
 '2018-12-31 23:30:21',
 '2018-12-31 23:30:20',
 '2018-12-31 23:30:14',
 '2018-12-31 23:30:13',
 '2018-12-31 23:30:09',
 '2018-12-31 23:29:58',
 '2018-12-31 23:29:44',
 '2018-12-31 23:29:39',
 '2018-12-31 23:29:33',
 '2018-12-31 23:29:32',
 '2018-12-31 23:29:31',
 '2018-12-31 23:29:27',
 '2018-12-31 23:29:20',
 '2018-12-31 23:29:19',
 '2018-12-31 23:29:17',
 '2018-12-31 23:29:15',
 '2018-12-31 23:29:11',
 '2018-12-31 23:29:02',
 '2018-12-31 23:28:58',
 '2018-12-31 23:28:55',
 '2018-12-31 23:28:53',
 '2018-12-31 23:28:52',
 '2018-12-31 23:28:48',
 '2018-12-31 23:28:47',
 '2018-12-31 23:28:46',
 '2018-12-31 23:28:44',
 '2018-12-31 23:28:40',
 '2018-12-31 23:28:27',
 '2018-12-31 23:28:26',
 '2018-12-31 23:28:24',
 '2018-12-31 23:28:23',
 '2018-12-31 23:28:11',
 '2018-12-31 23:28:10',
 '2018-12-31 23:28:09',
 '2018-12-31 23:28:06',
 '2018-12-31 23:28:05',
 '2018-12-31 23:28:04',
 '2018-12-31 23:27:59',
 '2018-12-31 23:27:47',
 '2018-12-31 23:27:42',
 '2018-12-31 23:27:40',
 '2018-12-31 23:27:38',
 '2018-12-31 23:27:32',
 '2018-12-31 23:27:31',
 '2018-12-31 23:27:30',
 '2018-12-31 23:27:25',
 '2018-12-31 23:27:19',
 '2018-12-31 23:27:10',
 '2018-12-31 23:27:09',
 '2018-12-31 23:27:05',
 '2018-12-31 23:27:04',
 '2018-12-31 23:27:01',
 '2018-12-31 23:27:00',
 '2018-12-31 23:26:58',
 '2018-12-31 23:26:54',
 '2018-12-31 23:26:50',
 '2018-12-31 23:26:38',
 '2018-12-31 23:26:33',
 '2018-12-31 23:26:32',
 '2018-12-31 23:26:30',
 '2018-12-31 23:26:23',
 '2018-12-31 23:26:18',
 '2018-12-31 23:25:59',
 '2018-12-31 23:25:58',
 '2018-12-31 23:25:55',
 '2018-12-31 23:25:54',
 '2018-12-31 23:25:49',
 '2018-12-31 23:25:48',
 '2018-12-31 23:25:47',
 '2018-12-31 23:25:46',
 '2018-12-31 23:25:42',
 '2018-12-31 23:25:40',
 '2018-12-31 23:25:39',
 '2018-12-31 23:25:35',
 '2018-12-31 23:25:26',
 '2018-12-31 23:25:23',
 '2018-12-31 23:25:21',
 '2018-12-31 23:25:19',
 '2018-12-31 23:25:16',
 '2018-12-31 23:25:13',
 '2018-12-31 23:25:12',
 '2018-12-31 23:25:11',
 '2018-12-31 23:25:08',
 '2018-12-31 23:25:07',
 '2018-12-31 23:25:05',
 '2018-12-31 23:24:58',
 '2018-12-31 23:24:54',
 '2018-12-31 23:24:52',
 '2018-12-31 23:24:46',
 '2018-12-31 23:24:45',
 '2018-12-31 23:24:43',
 '2018-12-31 23:24:40',
 '2018-12-31 23:24:35',
 '2018-12-31 23:24:34',
 '2018-12-31 23:24:23',
 '2018-12-31 23:24:21',
 '2018-12-31 23:24:19',
 '2018-12-31 23:24:17',
 '2018-12-31 23:24:14',
 '2018-12-31 23:24:06',
 '2018-12-31 23:23:55',
 '2018-12-31 23:23:52',
 '2018-12-31 23:23:49',
 '2018-12-31 23:23:44',
 '2018-12-31 23:23:32',
 '2018-12-31 23:23:30',
 '2018-12-31 23:23:26',
 '2018-12-31 23:23:25',
 '2018-12-31 23:23:21',
 '2018-12-31 23:23:14',
 '2018-12-31 23:23:11',
 '2018-12-31 23:23:10',
 '2018-12-31 23:23:09',
 '2018-12-31 23:23:05',
 '2018-12-31 23:23:02',
 '2018-12-31 23:23:00',
 '2018-12-31 23:22:59',
 '2018-12-31 23:22:58',
 '2018-12-31 23:22:56',
 '2018-12-31 23:22:52',
 '2018-12-31 23:22:48',
 '2018-12-31 23:22:45',
 '2018-12-31 23:22:42',
 '2018-12-31 23:22:41',
 '2018-12-31 23:22:39',
 '2018-12-31 23:22:38',
 '2018-12-31 23:22:28',
 '2018-12-31 23:22:27',
 '2018-12-31 23:22:22',
 '2018-12-31 23:22:17',
 '2018-12-31 23:22:16',
 '2018-12-31 23:22:13',
 '2018-12-31 23:22:07',
 '2018-12-31 23:22:05',
 '2018-12-31 23:22:04',
 '2018-12-31 23:21:58',
 '2018-12-31 23:21:57',
 '2018-12-31 23:21:48',
 '2018-12-31 23:21:46',
 '2018-12-31 23:21:45',
 '2018-12-31 23:21:43',
 '2018-12-31 23:21:38',
 '2018-12-31 23:21:31',
 '2018-12-31 23:21:27',
 '2018-12-31 23:21:20',
 '2018-12-31 23:21:18',
 '2018-12-31 23:21:17',
 '2018-12-31 23:21:15',
 '2018-12-31 23:21:14',
 '2018-12-31 23:21:09',
 '2018-12-31 23:21:08',
 '2018-12-31 23:21:07',
 '2018-12-31 23:21:05',
 '2018-12-31 23:21:04',
 '2018-12-31 23:21:02',

In [ ]:
'''Vectors Analysis:
---------------------
- VendorID is the cab company.
        1 = Creative Mobile Technologies, LLC; 
        2 = VeriFone Inc.
- Pickup and dropoff vectors have to be stripped. ['2008-12-31 23:43:29', .... '2019-03-11 22:34:23'] Ten years worth of trips.
- RateCodeID {1, 2, 3, 4, 5, 6, 99} values need to be relabled matching the data dictionary. There is a 99 value not defined.
        1 = Standard rate
        2 = JFK
        3 = Newark
        4 = Nassau or Westchester
        5 = Negotiated fare
        6 = Group ride
- Passanger Count: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
- Trip Distance {0.0, 0.01, , .. 33.64 ...105.13} in miles.
- Payment Type: {1, 2, 3, 4, 5} values need to be relabled matching the data dictionary. Value 6 is missing.
        1 = Credit card
        2 = Cash
        3 = No charge
        4 = Dispute
        5 = Unknown
        6 = Voided trip
- Trip type: {1,2}
        1 = Street-hail
        2 = Dispatch


Money Related Vectors:
---------------------
- Fare Amount: {0.0,....,495.0, 500.0} assumed all the same currency.
- Extra: [4.5, 1.0, 0.72, 0.5, 0.0, -0.5, -1.0, -4.5] This conflicts with the data dictionary.
- MTA Tax : [0.5, 0.08, 0.0, -0.5] in dollars.
- Tip Amount: [-8.88,-8.0,-1.26, ....... 300.0] There are negative tips.
- Tolls Amount: [-11.52,0.0, .... 59.76, 95.76] There are negative tolls.
- Ehail Fee: [...]
- Improvement Surcharge: [...]
- Total Amount: metric

Less Usefull Vectors:
--------------------
May not be too relevant: Store_and_fwd_flag {Y,N}
Location vectors are missing name dimension table - PULocationID and DOLocationID  {1,2,3,4 .... , 265}.
Location vectors contain too many values for a simple agregations.

'''

In [ ]:
#TEST DESIGNATED AREA

In [11]:
#TEST POWER BI MEAN VISUALIZATION
df0.groupby(['VendorID']).mean()

,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type
VendorID,,,,,,,,,,,,,,,
1,1.089262,110.198398,128.403983,1.146992,3.090868,13.042764,0.331109,0.489157,1.320538,0.159751,NaN,0.293770,15.637090,1.488996,1.019389
2,1.300430,110.328903,128.075217,1.349826,3.498454,14.311278,0.304246,0.488862,0.877771,0.245640,NaN,0.275565,16.532044,1.401874,1.073989

In [19]:
#TEST POWER BI DISPATCH COUNT VISUALIZATION
df1 = df0.iloc[:,[0,18]]
df1.groupby(['trip_type']).count()

           VendorID
trip_type
1.0          640290
2.0           45081